project:
  type: website
  output-dir: docs

website:
  title: "Amorae Times"
  navbar:
    background: light
    left: 
      - text: "Home"
        href: index.qmd
      - text: "About" 
        href: about.qmd
      - text: "Research"
        menu:
          - text: "Papers in Progress"
            href: progress.qmd
          - text: "Publications"
            href: publications.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Notes"
        href: notes.qmd
      - text: "News"
        href: news.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/amorae-times-02226b122/
  page-footer:
    center: "© {date:YYYY} Amorae Times"


format:
  html:
    toc: true
    toc-location: left
    smooth-scroll: true
    theme:
      - cosmo
      - assets/theme.scss
    css: assets/custom.css
    code-link: false

metadata-files:
  - _site-meta.yml

