---
title: "Teaching"
---

As a lifelong student, I believe that student success grows from collaboration, sustained effort, and a growth mindset. My teaching philosophy centers on creating a supportive and engaging classroom environment that fosters mutual respect, academic curiosity, and intellectual rigor. I encourage active participation, clear and timely communication, and a strong commitment to learning. For me, education extends beyond the transmission of knowledge; it is about cultivating critical thinking, sharpening problem-solving skills, and inspiring a passion for lifelong learning. I challenge students to move beyond their comfort zones, engage with diverse perspectives, and embrace new ways of thinking. At the same time, I am committed to providing the resources and mentorship that allow students to succeed both academically and personally—whether through one-on-one meetings, virtual office hours, or interactive learning platforms. My goal is to help students reach their full potential and leave the classroom equipped to engage thoughtfully with the world around them.
